package com.cargotrack.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESHED,
    SUSPICIOUS_REFRESH_REUSE,
    USER_REGISTERED,
    EMPLOYEE_CREATED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ROLE_CHANGED,
    PARCEL_CREATED,
    PARCEL_CANCELLED,
    PARCEL_STATUS_CHANGED,
    SHIPMENT_CREATED,
    SHIPMENT_PARCEL_ASSIGNED,
    SHIPMENT_PARCEL_REMOVED,
    SHIPMENT_DEPARTED,
    SHIPMENT_ARRIVED,
    TRUCK_CREATED,
    TRUCK_UPDATED,
    TRUCK_DELETED,
    WAREHOUSE_CREATED,
    WAREHOUSE_UPDATED,
    WAREHOUSE_DELETED
}
